<?php
function shift_cipher_menu() {
    $items['shift_cipher'] = array(
        'title' => 'Shift Cipher',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('shift_cipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['shift_cipher_success'] = array(
        'title' => 'Success',
        'page callback' => 'shift_cipher_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function shift_cipher_form() {
    $form['shift_value'] = array(
        '#title' => 'shift value',
        '#type' => 'textfield',
        '#element_validate' => array('element_validate_integer_positive'),
        '#description' => t('Enter number of places by which to shift each letter'),
    );
    $form['direction'] = array(
        '#title' => 'direction',
        '#type' => 'radios',
        '#options' => array('left' => 'left', 'right' => 'right'),
        '#description' => t('Choose direction of shift'),
    );
    $form['phrase'] = array(
        '#title' => 'phrase',
        '#type' => 'textfield',
        '#element_validate' => array('element_validate_proper_phrase'),
        '#description' => t('Enter phrase to encrypt'),
    );
    $form['submit'] = array(
        '#value' => 'Encrypt!',
        '#type' => 'submit',
    );
    return $form;
}

function shift_cipher_form_submit($form, &$form_state) {
    $_SESSION['shift_value'] = $form_state['values']['shift_value'];
    $_SESSION['direction'] = $form_state['values']['direction'];
    $_SESSION['phrase'] = $form_state['values']['phrase'];
    $form_state['redirect'] = 'shift_cipher_success';
}

function shift_cipher_success() {
    return '<p>shift value = ' . $_SESSION['shift_value'] . '</p><p>direction = ' . $_SESSION['direction'] . '</p><p>phrase = ' . $_SESSION['phrase'] . '</p>';
}

function element_validate_proper_phrase($element) {
    $phrase = $element['#value'];
    $element_title = $element['#title'];

    $chars = str_split($phrase);

    foreach ($chars as $char) {
        if (!(ctype_alpha($char) || ctype_space($char) || ctype_punct($char))) {
            form_error($element, t("$element_title must contain only letters, spaces, and punctuation"));
        }
    }
}
